version: 2
 
jobs:
 build:
   docker:
     - image: circleci/ruby:2.6.5
   steps:
     - checkout
     - run: echo "A first hello"
 build:
   docker:
     - image: circleci/ruby:2.6.5
   steps:
     - checkout
     - run: echo "A first hello"
  test:
    docker:
      - image: circleci/ruby:2.6.5
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Run test
          command: 'ruby test_sum.rb'
workflows:
  version: 2
  workflows:
    jobs:
      - test
